### ISSUE TITLE
压缩后的图片反而变大了，附图。

### ISSUE THREAD

**Issue by Femtometer** [Mikachu2333/rimage_gui#11]
RT.

![截图_2023-12-18_15-48-17](https://github.com/Mikachu2333/rimage_gui/assets/5461891/fca1e2b1-e832-4881-a5c3-a0095f8cefc4)

**Comment by Mikachu2333** [comment]
经简单观察，不计划对此进行优化或向原作者反馈。

因图片原始体积极小，已不再传统意义上的压缩定义之内。通常本软件的作用范围是1M-10G左右的文件，低于1M的图片均无法有效降低体积，敬请知悉。

如确实需要压缩，直接往上面糊一层轻微马赛克或使用qq、微信、百度贴吧等均可快速实现你所需要的结果，本软件现有的效果确实无法满足你的需求。
