### ISSUE TITLE
想要记住上次选择

### ISSUE THREAD

**Issue by LyntNy4n** [Mikachu2333/rimage_gui#12]
也就是说需要一个配置文件

**Comment by Mikachu2333** [comment]
现阶段不考虑，因为个人坚持绿色无污染，也就是说不会写注册表与保存配置文件，方便删除时直接delete，而无论那种方式都会破坏掉现有的“绿色无污染”，这在我看来是不可接受的……早就受够了垃圾软件到处拉屎的情况，我可不想自己的软件也变成那个鬼样子……

**Comment by LyntNy4n** [comment]
> 现阶段不考虑，因为个人坚持绿色无污染，也就是说不会写注册表与保存配置文件，方便删除时直接delete，而无论那种方式都会破坏掉现有的“绿色无污染”，这在我看来是不可接受的……早就受够了垃圾软件到处拉屎的情况，我可不想自己的软件也变成那个鬼样子……

配置文件放exe旁边也能方便删除啊 主要是默认设定不一定能满足所有人的要求 每一次用都得去改

**Comment by Mikachu2333** [comment]
它难看啊可是……这种样子已经是我能接受的极限了……再多一个配置文件……已经想把这个软件从我的电脑里面移除了…… 
![图片](https://github.com/Mikachu2333/rimage_gui/assets/63829496/3d0ecbd5-bce6-40f6-b137-77c7539f4a12)

**Comment by LyntNy4n** [comment]
我倒觉得还好 反正都是放在一个文件夹里的
反正能保存设定肯定是更实用的
也许有方法可以保存设定同时不需要配置文件? 我就不清楚了

**Comment by Mikachu2333** [comment]
> 也许有方法可以保存设定同时不需要配置文件? 我就不清楚了

太有了，注册表，驱动，服务等等但那更恶心……

**Comment by Mikachu2333** [comment]
> 也许有方法可以保存设定同时不需要配置文件? 我就不清楚了

太有了，注册表，驱动，服务等等但那更恶心……

**总之，还是暂不考虑吧**，尤其是现在的功能就这几个，完全没有必要用配置文件。如果是几十个功能的话我可能还会考虑……
