### ISSUE TITLE
[Feature] 使图片在自动原目录下新建一个子目录并输出

### ISSUE THREAD

**Issue by 52linglong** [Mikachu2333/rimage_gui#13]
能否支持原目录下新目录输出？
如：智图 压缩后 《zhitu-des》目录下输出。
![智图_客户端-2024-01-26_23-43-11](https://github.com/Mikachu2333/rimage_gui/assets/51982959/d6798dd3-3c6e-4772-8156-2e9ea57aca9a)
![-2024-01-26_23-42-28](https://github.com/Mikachu2333/rimage_gui/assets/51982959/a093098b-5e3a-4b34-9397-fb00434ab171)

**Comment by Mikachu2333** [comment]
支持的啊，你把“原目录输出”取消勾选，然后双击输出目录即可

**Comment by 52linglong** [comment]
输出目录是指定单目录输出，是否支持多目录（‘文件列表‘不同目录下的文件），原目录下新目录输出？

如：A/A.jpg，B/B.png，C/C.jpg 输出webp格式 A/out/A.webp，B/out/B.webp，C/out/C.webp。

**Comment by Mikachu2333** [comment]
这个没有支持，如果提议的人多了可以考虑加一下，感觉，提出这个建议的人比较少（笑哭）

还有一点小担心就是这么干会不会继续疯狂报毒啊……好不容易从各大杀软的黑名单里解放出来（捂脸）

**Comment by 52linglong** [comment]
![XnConvert-2024-01-27_17-58-23](https://github.com/Mikachu2333/rimage_gui/assets/51982959/0d0a53f7-a40e-4cab-b2dc-cf41902452ed)

**Comment by Mikachu2333** [comment]
> 输出目录是指定单目录输出，是否支持多目录（‘文件列表‘不同目录下的文件），原目录下新目录输出？
> 
> 如：A/A.jpg，B/B.png，C/C.jpg 输出webp格式 A/out/A.webp，B/out/B.webp，C/out/C.webp。

我给你问问rimage的原作者吧，我看看他有没有计划加，要是他有计划加那我这个gui就坐享其成，要是他没计划加我就做一个
（本人水平有限，只能支持简单的分类）

---

例如（文件名称新增后缀仍可自选）：
|原始|输出|
|-- | -- |
|`D:\\test\\1.jpg`|`D:\\test\\jpg\\1_updated.jpg`|
|`C:\\before\\5.png`|`C:\\before\\webp\\5_updated.webp`|

如果我做，暂定实现目标：
1. 输出到原目录下的新目录时，新目录的名称可以自定义（仅读取用户输入，因水平不够，无法提供正则支持）

---

另：还是很好奇你的需求到底是为啥（狗头），因为我想了一圈也没想明白需求的目的

**Comment by Mikachu2333** [comment]
完工
