### ISSUE TITLE
Typos in the description

### ISSUE THREAD

**Issue by sooxin** [Mikachu2333/rimage_gui#14]
疑似错字：

- `opinion` -> `option`
- `hovor` -> `hover`

![image](https://github.com/Mikachu2333/rimage_gui/assets/16705366/fa2a5b14-fb73-4a95-b7e3-e528bbf1e759)

很棒的小工具，感谢 @Mikachu2333 的辛勤付出❤

**Comment by Mikachu2333** [comment]
太对了……才发现我一直把option拼成了opinion……
这就改
