### ISSUE TITLE
如何指定mozjpeg?

### ISSUE THREAD

**Issue by LyntNy4n** [Mikachu2333/rimage_gui#20]
rimage cli中可以指定不同的codec 但是这里只有一个选项 我怎么知道当前用的什么codec呢?

**Comment by Mikachu2333** [comment]
jpg选项就是默认的mozjpeg的，原图片用的什么codec是不知道的，软件只负责转换后的codec正确（

此外，原CLI的preview版本没有本GUI跟进，我还在和原软件作者掰扯颜色错误的问题……得等那边修了我再改GUI发版，如果有需求可以先用着那边最新的preview版本

其他问题还有吗，或者说我有哪里没解释清楚？

**Comment by Mikachu2333** [comment]
没有输出jpg codec的选项，GUi里的`jpg`对应且仅对应mozjpeg codec，为啥？我懒，省略了（

**Comment by Mikachu2333** [comment]
对了，除了`mozjpeg codec`对应`jpg format`，`oxipng codec`对应`png format`以外，其余的format都是与codec在名称上完全对应的

（其实都是完全调用的rimage的默认设置。举例，传个jpg的参给rimge，它会直接调用moz的codec而非jpeg codec，png也是同理）

下一步的GUI会对此进行进一步明确的（不过还想兼顾小白用户，所以jpg和png选项只会加个解释，说是实际调用了哪种codec但是不会直接显示）

**Comment by LyntNy4n** [comment]
那就没问题了 建议在readme上说下这个默认设定

**Comment by Mikachu2333** [comment]
> 那就没问题了 建议在readme上说下这个默认设定

收到，我给 #19 加一条去
