### ISSUE TITLE
输入AVIF文件格式的图片不能转换

### ISSUE THREAD

**Issue by xnuxmwx** [Mikachu2333/rimage_gui#22]
输入：AVIF格式图片
输出：任意格式
结果：提示转换成功，但实际不能输出

**Comment by Mikachu2333** [comment]
我看看

**Comment by Mikachu2333** [comment]
是成功的，只不过输出目录有点小问题 🤣 正在修复中……

你可以使用everything之类的看一下输出到哪个奇怪目录里面去了……

**Comment by Mikachu2333** [comment]
修复完毕，现在我这边测着没问题了
