### ISSUE TITLE
can't compress some photos.

### ISSUE THREAD

**Issue by Alliskyline2020** [Mikachu2333/rimage_gui#24]
because there's no logfile, I tried to get the exif info. of Can/Can't compress files
But only find the size different, other info. are the same.
Thanks a lot for your great project and product! It helps me a lot during my office time!

Can
ExifTool Version Number         : 13.03
File Size                       : 11 MB
Image Width                     : 4470
Image Height                    : 1621
Image Size                      : 4470x1621
Megapixels                      : 7.2

Can't
ExifTool Version Number         : 13.03
File Size                       : 200 MB
Image Width                     : 24198
Image Height                    : 8640
Image Size                      : 24198x8640
Megapixels                      : 209.1

**Comment by Mikachu2333** [comment]
Your pic's width is to big for rimage to cov. Please resize it first with the following settings that pic shows first, and then compress your pic or cov it to other format.
![图片](https://github.com/user-attachments/assets/f88ee707-19a8-4a15-8cda-55b7437cfc64)

**Comment by Mikachu2333** [comment]
You can hover over the resize edit_box to see tips.
