### ISSUE TITLE
feature request: provide x64 version

### ISSUE THREAD

**Issue by ivysrono** [Mikachu2333/rimage_gui#4]

**Comment by Mikachu2333** [comment]
Thanks for advices! I'd like to support it after the Final Exam on summer vacation!

**Comment by Mikachu2333** [comment]
Bad news. After learning the aardio program language competely, I noticed that it doesn't support making the x64 version. To provide x64 version, I had to learn Rust to make it as a alternative selection....

**Comment by Mikachu2333** [comment]
Bad news. After learning the aardio program language competely, I noticed that it doesn't support making the x64 version. To provide x64 version, I had to learn Rust to make it as a alternative selection....
