### ISSUE TITLE
Shifted colors

### ISSUE THREAD

**Issue by studioj2y** [Mikachu2333/rimage_gui#7]
Color is shifted significantly, for example,
![0001](https://github.com/Mikachu2333/rimage_gui/assets/61308545/c1eeb627-acbe-47ce-825a-8096ec7a2f2a)
![0001_updated](https://github.com/Mikachu2333/rimage_gui/assets/61308545/dd3990d6-1db4-4526-9074-442d5890e5ff)

face and lips lost red and pink tones

**Comment by Mikachu2333** [comment]
Please reset all choices to the max and just change the quality choice. This may assist you improve the pic color
