### ISSUE TITLE
名字有特殊符号话则转换出错

### ISSUE THREAD

**Issue by ACERdPHE** [Mikachu2333/rimage_gui#8]
原图文件夹名字含有符号如‘[ ] /’等则无法生成新图
原图名字含有'-'则程序不能识别原图‘-’后面数字导致不停生成相同名字不能内容的新图
不勾选‘自动删除’选项仍然会在转换完成后删除原图。

程序版本号：1.0.5.34
平台：win10 x64

**Comment by Mikachu2333** [comment]
经查，原程序未能识别导致本程序传参错误导致。已反馈

**Comment by Mikachu2333** [comment]
新版已解决，pre版带有黑色cmd窗口，单线程，其余未变，可用此版先行测试可用性；本周将发布正式版大更新，解决刚刚的所有问题。
