### ISSUE TITLE
（特殊符号问题）没转换文件便删除了文件。。

### ISSUE THREAD

**Issue by Smile8848** [Mikachu2333/rimage_gui#9]
刚试着压缩本子光删文件啥也没输出。。

**Comment by Smile8848** [comment]
"G:\本[大文件]\11111\[雛原えみ] 夢現ロマンティック [未來數位中文] [無修正]\[雛原えみ] 夢現ロマンティック [未來數位中文] [無修正]"
这是路径。。

**Comment by Smile8848** [comment]
![image](https://github.com/Mikachu2333/rimage_gui/assets/31927778/fc9eb9ea-ec2a-468b-ac37-08108f032347)

**Comment by Mikachu2333** [comment]
你这和上一个issue说的是同一个问题，都是由于特殊符号导致的，是因为原程序设计不周导致的，已经向原本的开发者反馈了，正在等待开发者解决。

**Comment by Smile8848** [comment]
> 你这和上一个issue说的是同一个问题，都是由于特殊符号导致的，是因为原程序设计不周导致的，已经向原本的开发者反馈了，正在等待开发者解决。

收到。

**Comment by Mikachu2333** [comment]
新版已解决，pre版带有黑色cmd窗口，单线程，其余未变，可用此版先行测试可用性；本周将发布正式版大更新，解决刚刚的所有问题。
